### ISSUE TITLE
Gitcoin Grants && EthScalingFunding.com

### ISSUE THREAD

**Issue by owocki** [ethhub-io/ethhub#104]
Hi there,

Just wanted to comment on https://github.com/ethhub-io/ethhub/blob/master/other/ethereum-fundraising-event.md but didnt see a good way to do so.

We're trying to position [Gitcoin Grants](https://gitcoin.co/grants), which just launched, to make it a kind of decentralized Patreon.  The idea is that the one-time grants the ECF/EF have been giving are a great one-time capital injection, but that projects need recurring funding in order to be able to focus on their missions.

Note Gitcoin Grants is not exactly as you specified on ethereum-fundraising-event.md, as you all specified a more kickstarter-style funding whereas ours is planned to be more Patreon-style.

Is there a way we can get an invite to wherever the convos around EthScalingFunding.com are happening?

Best,
Kevin

**Comment by cyber-hokie** [comment]
@econoar you slacker... the great Owoki requests and audience for further discussion!

**Comment by ethhub-io** [comment]
@owocki we are working on building out a channel right now where people can talk about EthHub related items like this. I'll send you an invite within the next couple of days.

**Comment by arektdev** [comment]
@ethhub-io Hello. Is there a discord server for this yet?

**Comment by econoar** [comment]
https://discordapp.com/invite/gw8AM98
