### ISSUE TITLE
Monetary Policy

### ISSUE THREAD

**Issue by 5chdn** [ethhub-io/ethhub#118]
Good morning.

Regarding: https://docs.ethhub.io/ethereum-basics/monetary-policy

Ether was never considered as currency and therefore, Ethereum never had a monetary policy. While this information on that page is mostly accurate, it might indicate for users that Ethereum indeed has an official policy. What do you think, shall we rename the page?

Also, block reward reduction is just something to stabilize the issuance, so it might be worth to underline why the block reward was reduced (while the bomb was delayed).

**Comment by sassal** [comment]
Hey Afri!

That's a point good - we don't want to be giving the impression that there is an 'official' monetary policy for Ethereum (as its decided upon by a multitude of different stakeholders). I'm open to suggestions for a new name if you have any!

Agree on the block reward point too - I'll let @econoar reword it once he's online as this document was originally created by him.

**Comment by Nemris** [comment]
The argument for whether ether is currency does not turn on whether it was (or wasn't) considered currency at time T-1 by group X. It turns on whether it is considered currency by readers of ethhub at the present time.

But even if you reject that assertion, you still have the problem that your case may be unsound. 
Premise 1: "Ether was never considered as currency"
Conclusion: "therefore..."

What support do you have for Premise 1? Are we talking about ether being considered as currency by founders? By developers? By users? At what point does the consideration need to happen for ether to be called currency? If ether is considered currency in 2019, is it relevant that it wasn't considered currency by group X in 2014?

**Comment by ChazSchmidt** [comment]
I think the best compromise might be to leave the page name as monetary policy and then include a section covering the history and debate over the terms, issuance etc.

**Comment by 5chdn** [comment]
> I think the best compromise might be to leave the page name as monetary policy and then include a section covering the history and debate over the terms, issuance etc.

+1

**Comment by sassal** [comment]
I agree with @ChazSchmidt. I can work something up tomorrow unless someone else gets to it first :)
