### ISSUE TITLE
Ether is fungible - contradiction

### ISSUE THREAD

**Issue by tbm** [ethhub-io/ethhub#130]
https://docs.ethhub.io/ethereum-basics/what-is-ether/medium-of-exchange says:

> Either is highly... and fungible (ether isn’t really fungible since accounts can be blacklisted quite easily

So you say it's highly fungible but in brackets you say it's not?

**Comment by sassal** [comment]
Good catch! I just committed a bunch of changes I had been working on for that page - check it out and let me know what you think :)

**Comment by tbm** [comment]
Thanks, this was indeed addressed in af7ded9cc13d3d
