### ISSUE TITLE
Mention the Howey test

### ISSUE THREAD

**Issue by tbm** [ethhub-io/ethhub#132]
It would be nice to mention (and explain) the Howey test somewhere, maybe in a chapter on ICOs and STOs, or at least a glossary.

**Comment by ChazSchmidt** [comment]
+1. Quoting the SEC here is a must. Maybe even citing https://www.howeycoins.com/index.html (https://investor.gov/howeycoins)

**Comment by haokaiwu** [comment]
@tbm Check out my most recent pull request. I added a section about the Howey test to explain why Ether will likely not be classified a security.

**Comment by tbm** [comment]
@haokaiwu PR #147 looks good to me (but I'm not an expert). Thanks

**Comment by sassal** [comment]
Yep - merged @haokaiwu's work on https://github.com/ethhub-io/ethhub/pull/147 - great stuff!
