### ISSUE TITLE
Proposal: simplify DEX classification

### ISSUE THREAD

**Issue by Destiner** [ethhub-io/ethhub#141]
We have an awesome collection of DEXs with the description of their mechanics and how they differ from each other.

One thing that I think can be improved is the categories that we have for "DEX" section. I see two problems here: too many categories and long descriptions.

Also, there are also some doubts about where we need to put each DEX. For example, EtherDelta/ForkDelta seems to have order book off-chain and delivered over API, similarly to 0x.

Republic Protocol can be seen as a peer-to-peer DEX, as there's no global pool or relay to aggregate orders, as they are matched with each other on a case by case basis.

I propose the following classification:
* peer-to-peer (Republic Protocol, Airswap)
* off-chain order book (0x, Etherdelta, Hydro, etc)
* pool-based (Uniswap, Bancor, Kyber)

**Comment by sassal** [comment]
Agreed - the DEX section could definitely use a clean up. I should be able to get to it within the next 24 hours unless you had some spare time to get the changes going yourself :)
