### ISSUE TITLE
Include definition of archive node in running a node section

### ISSUE THREAD

**Issue by oliver-ernst** [ethhub-io/ethhub#142]
Hello,

On the "Running a node" page, I'm just wondering if someone with the relevant knowledge could include a sentence or two about what the archive mode on geth and parity actually is, maybe why it's so much bigger and if it offers any additional security to the network by running this mode.  

I just don't really understand this mode and would love a simple explanation as to why it's more than 10 times the size of a full node.

Thank you.

**Comment by sassal** [comment]
@cyber-hokie was looking into this if I remember correctly!

**Comment by sassal** [comment]
Hey @oliver-ernst.

We added a description to the [Running an Ethereum Node](https://github.com/ethhub-io/ethhub/blob/master/using-ethereum/running-an-ethereum-node/README.md).

"Archive nodes are only necessary if you want to check the state of an account at any given block height. For example, if you wanted to know the Ether balance an account had at block #4,000,000, you would need to run and query an archive node.

They are commonly only used for services such as block explorers and infrastructure providers like Infura."

**Comment by oliver-ernst** [comment]
Thank you for the definition, makes sense and is easy to understand.  Thanks for the hard work you are all contributing to this project.
