### ISSUE TITLE
Good Security Token Offerings (STO) link

### ISSUE THREAD

**Issue by tbm** [ethhub-io/ethhub#145]
This is a good article about STOs: [All you Need to Know about Security Token Offerings (STO)](https://guerrillabuzz.com/all-you-need-to-know-about-security-token-offerings-sto/)

It could be added to the references or as part of a chapter on ICO/STO (see #132)

**Comment by sassal** [comment]
The resource is good but unfortunately the website offers services such as "ICO Marketing" which we don't want promoted and associated with EthHub.

Maybe theres a Medium article out there with similar information?

**Comment by tbm** [comment]
Fair enough. The site looked a bit weird (didn't look closely) but the article was pretty good. I'll see if there's another article.

**Comment by tbm** [comment]
https://www.cointelligence.com/content/security-token-offering-sto-how-to/ (not sure that site is ok)

https://medium.com/swlh/understanding-security-token-offerings-sto-bc272acd3f27 (but not as complete)

https://tokeny.com/the-pros-and-cons-of-security-token-offerings/ (not sure if ok)

**Comment by Yuval-Halevi** [comment]
@sassal 
I wrote the article.
GuerrillaBuzz is indeed a marketing agency so I understand why you can't refer to the article.

For that purpose, I also launched the same article on [Medium](https://medium.com/guerrillabuzz/all-you-need-to-know-about-security-token-offerings-stos-guerrillabuzz-62dd37c7cf7a?source=collection_home---1------2---------------------) 

I hope it helps :)

**Comment by ChazSchmidt** [comment]
Has this issue been solved?
