### ISSUE TITLE
Contribution guidelines

### ISSUE THREAD

**Issue by liamzebedee** [ethhub-io/ethhub#16]
Hey mate, this just popped up on my feed. Seems like you've got some great content here! I'd love to donate my content here for contribution - https://github.com/liamzebedee/awesome-solidity-patterns. Let me know if that'd be desired and if so, how. We need better documentation in Ethereum!

**Comment by sassal** [comment]
Hey Liam,

That's an awesome bunch of resources you've put together.

I've created a new folder called 'Development' for you (https://github.com/econoar/ethhub/tree/master/ethereum-101/development). Feel free to submit pull requests with content that you'd like to add (from beginner guides to more advanced solidity things) and we can work on building it up together.

Thanks!

**Comment by liamzebedee** [comment]
Awesome! Quite busy searching for a house atm - I'm gonna take a read through your docs and try to understand the flow of the book. Then I can probably port some content over :)

**Comment by sassal** [comment]
Sounds good :)

Just a note - Ethhub is going to be a website (basically a docs platform that pulls the info from github) so think of it in the flow of menus>submenus!

**Comment by hatgit** [comment]
Thought to leave this here as a potential resource/list of DEXs: https://github.com/distribuyed/index

**Comment by econoar** [comment]
contribution guidelines now up
