### ISSUE TITLE
What's your incentive for doing this project?

### ISSUE THREAD

**Issue by ArtemBernatskyy** [ethhub-io/ethhub#178]
Awesome project, but after reading through website I've found lots of mentions of ICOs which could be a paid advertisement.

So we need to ask - what's your incentive to do this project?
How it is funded?
How are you related to Ethereum?

Thx.

**Comment by sassal** [comment]
Hey Artem,

We try our hardest to avoid having any ICO-related advertisements (or any advertisements) displayed on the website. Are you able to point me towards the content you're talking about?

We haven't been paid for any content on the site and we're entirely self-funded and independent.

**Comment by econoar** [comment]
I suppose I'll round out the trio here but I have not made a dime from EthHub. In fact, we've lost a decent amount running it...

There are no paid ICO ads on the page. I would be interested in what you're referring to as well.

Cheers

**Comment by ArtemBernatskyy** [comment]
So, in other words, you are not related to Ethereum Foundation in any way.
And any tokens mentioned in EthHub isn't investing advice.

**Comment by sassal** [comment]
No, we are completely independent.

The pages for projects that have associated tokens are for information purposes only and should not be taken as investment advice or endorsement.

**Comment by ArtemBernatskyy** [comment]
Thx, closing this issue.

CC @econoar , I've wrote `could be a paid`, so I can't prove it and you can't prove opposite.
Because I am failing to see any incentive except pure enthusiasm, which we need to treat with a fair bit of caution.
