### ISSUE TITLE
Adding logo.png as favicon that is currently missing from site.

### ISSUE THREAD

**Issue by digitalisland** [ethhub-io/ethhub#192]
I've noticed there is no Favicon showing up on Brave, Chrome, or Firefox. 

logo.png from the front page looks like the right file to use. 

I know how to add this using my own websites using Transmit. Am a bit of a Github noob though so not quite sure what the procedure is here.

**Comment by ChazSchmidt** [comment]
Thanks for bringing it to our attention. I'll look into it.

**Comment by ethhub-io** [comment]
fixed!
