### ISSUE TITLE
Learn, Listen, Read on the homepage is confusing

### ISSUE THREAD

**Issue by stellarmagnet** [ethhub-io/ethhub#211]
I thought "Read" would take me to the Wiki

Suggested change -- just be more specific!

Wiki | Podcast | Newsletter

Alternatively: adding a the description under each word Learn, Listen, Read for where it is you are going

**Comment by digitalisland** [comment]
I concur with the OP.

**Comment by ChazSchmidt** [comment]
I have had this happen to me too. I'll have to take this into consideration for future changes.

**Comment by jjmstark** [comment]
Agree with this! Would be a useful change. 

Other options to name the "Learn" section could be "Knowledge base" or simply "docs"

**Comment by econoar** [comment]
fixed
