### ISSUE TITLE
Add explanation of common acronyms. 

### ISSUE THREAD

**Issue by jschiarizzi** [ethhub-io/ethhub#218]
For example:
- ERC : Ethereum Ready for Comment
- EIP : Ethereum Improvement Proposal
- TCR : Token Curated Registry. 

Too many throwing around acronyms makes learning challenging for beginners, especially when it is hard to find what things stand for.

**Comment by ChazSchmidt** [comment]
These can be found here. https://github.com/ethhub-io/ethhub/blob/master/docs/glossary/crypto-acronyms.md

Maybe we can find a way to incorporate this into other sections such as crosslinking.

**Comment by jschiarizzi** [comment]
Yes, that would be helpful,as I totally missed it. Thanks
