### ISSUE TITLE
add a landing page for "built on ethereum"

### ISSUE THREAD

**Issue by jjmstark** [ethhub-io/ethhub#254]
Currently, clicking on "built on ethereum" from the docs homepage takes the user directly to "Open Finance". 

This was unexpected, given that I clicked a link with a different name. It will be confusing to people who don't know what "Open Finance" means and understand that it is just the first sub-section in the "built on ethereum" category.

There should be a landing page for "built on ethereum" that provides based context like:
- There are many different applications built on ethereum
- these exist in many different categories, ranging from X to Y, which you can find more of in the navigation bar to the left
- [Maybe] include a master list of all apps built on ethereum that is contained in this section in one place (otherwise, there's no way to see all of them at once, without clicking into each subcategory of app

**Comment by econoar** [comment]
fixed and at https://docs.ethhub.io/built-on-ethereum/built-on-ethereum/ now. Let me know thoughts.

Cautious to add a huge list to that page of every dapp due to maintenance overhead.

**Comment by jjmstark** [comment]
Awesome! Looks great - makes sense about not adding every list, listing the app categories is a good substitute.
