### ISSUE TITLE
Chain size link defunct

### ISSUE THREAD

**Issue by Huge** [ethhub-io/ethhub#258]
At https://docs.ethhub.io/questions-about-ethereum/is-ethereum-over-1tb-in-size/ the first link "here" can't be loaded.

**Comment by sassal** [comment]
Nice catch! Replaced the link with https://www.nodestats.org/.

**Comment by Huge** [comment]
Nodestats declares itself discontinued.

**Comment by sassal** [comment]
Unfortunately yes - do you know of any other resources we can replace it with?

**Comment by marcuswin** [comment]
Can be closed, I fixed in #365
