### ISSUE TITLE
missing OGP and twitter cards at head

### ISSUE THREAD

**Issue by sneg55** [ethhub-io/ethhub#277]
When links from ethhub shared on social media they are missing nice preview and cover image. 

I think you have to implement OGP http://ogp.me/  and twitter cards https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary-card-with-large-image

**Comment by aranhaagency** [comment]
it is possible to add in this part of the project, send a pull request :)[ethhub/site](https://github.com/ethhub-io/ethhub/tree/master/site)

I will go now learning about OGP and twitter cards. 

good work
