### ISSUE TITLE
Rewrite the Plasma page

### ISSUE THREAD

**Issue by adlerjohn** [ethhub-io/ethhub#281]
The [Plasma page](https://github.com/ethhub-io/ethhub/blob/940920595ae5e3f8864f4e6f1b81af5617f19803/docs/ethereum-roadmap/layer-2-scaling/plasma.md) requires an almost complete rewrite. It contains a bunch of extraneous information, is outdated, and doesn't convey the actual benefits and shortcomings of Plasma accurately.

**Comment by sassal** [comment]
Do you know of anyone we should reach out to? We're happy to pay someone (in ETH or DAI) to write a proper page for it.

**Comment by adlerjohn** [comment]
Given that advancing research on layer-2 systems, in particular side chains, for the public Ethereum chain is literally my job, I'd be happy to do it. Though since we're in the public blockchain space, incentives are paramount. A gitcoin bounty would be enough to incentivize me to work on this (and maybe other qualified people!).

**Comment by sassal** [comment]
Bounty open: https://github.com/ethhub-io/ethhub/issues/285
