### ISSUE TITLE
Running an Ethereum Node - 5chdn link no longer hosted

### ISSUE THREAD

**Issue by shawnharmsen** [ethhub-io/ethhub#294]
Wanted to post here before submitting a PR.

defunct link: 
http://didtheethereumblockchainreach1tbyet.5chdn.co/

defunct link in this page:
https://docs.ethhub.io/using-ethereum/running-an-ethereum-node/

Was looking at wayback machine:
https://web.archive.org/web/20190207053336/http://didtheethereumblockchainreach1tbyet.5chdn.co/

I'm having trouble finding another source as useful as Afri's was

Would the following link work as a replacement?

1. geth and parity default
Full Node Sync with Default Settings
- https://etherscan.io/chartsync/chaindefault

**Comment by sassal** [comment]
I think we can use the Etherscan link for now - its unfortunate that Afris website no longer works!
