### ISSUE TITLE
No information on the ERC1257 page

### ISSUE THREAD

**Issue by sudeepb02** [ethhub-io/ethhub#314]
The ERC1257 page [here](https://docs.ethhub.io/built-on-ethereum/erc-token-standards/erc1257) is a blank page without any information on it. After searching for this ERC, I came across [this EIP here](https://github.com/ethereum/EIPs/issues/1257) which is still in the draft version, and no updates on this issue since last year. Should this page be removed? Or content to be added from the draft EIP?

**Comment by sassal** [comment]
Page deleted - thanks for the heads up :)
