### ISSUE TITLE
Fix broken links

### ISSUE THREAD

**Issue by jamesconnolly93** [ethhub-io/ethhub#320]
I Ran a scan for broken links and found the following. Apologies for the messy format of this issue, should have probably made a Google Sheet to track these. 

Monetary Policy.MD - links to Serenity phases broken
Eth 1.0 to 2.0 page had a broken link to Phases as well
Eth 2.0 AMA - same think with broken link to phases
Proof of Stake - link to Eth2.0 economics broken

On this menu https://docs.ethhub.io/built-on-ethereum/built-on-ethereum/ The following linked pages don't exist "Synthetix" stablecoin, "ERC 1257" token standard 

Under the 'Resources' section of https://docs.ethhub.io/ethereum-basics/ethereum-foundation/ the "EF Unicorn Directory" is broken. Tried to find an updated link but was unable.

https://docs.ethhub.io/ethereum-basics/development/tooling/ has a broken link to "Pragma" IDE as well as "getho"

https://docs.ethhub.io/questions-about-ethereum/is-ethereum-more-expensive-to-use-as-price-rises/ links to "Gas Section" and "Fee Market" are broken.

https://docs.ethhub.io/ethereum-basics/resources/ link to EthHub wallet section is broken. Link to EthHub Dex section is broken, link to "CryptoChat" is broken, link to "Atomic Bazaar" is broken, link to "Aragon DAO List" is broken

https://docs.ethhub.io/built-on-ethereum/decentralized-exchanges/off-chain-orderbook/what-is-off-chain-orderbook/ link to 0xProtocol broken

https://docs.ethhub.io/built-on-ethereum/identity/ERC-EIP/ link to ERC725 broken

https://docs.ethhub.io/built-on-ethereum/open-finance/8x/ link to protocol website is broken

https://docs.ethhub.io/built-on-ethereum/open-finance/nexus-mutual/ link to testnet demo is broken

**Comment by jschiarizzi** [comment]
@ChazSchmidt you could also add a 'Hacktoberfest' label to this

**Comment by MarkOSullivan94** [comment]
Working on these atm 👍

**Comment by MarkOSullivan94** [comment]
https://github.com/ethhub-io/ethhub/pull/353

**Comment by MarkOSullivan94** [comment]
@jamesconnolly93  @sassal this can be closed now
