### ISSUE TITLE
Clarifications or corrections

### ISSUE THREAD

**Issue by DigitalAssetAdvisors** [ethhub-io/ethhub#61]
**Blocks/epoch | 31536000/(6*64) = 82125**

Is the heading of "blocks/epoch" correct?  It appears the above formula is calculating "epochs/year", but the label is misleading. 

**Reward Quotient | 2048*INT(SQRT(10000000)) = 6475776**

The FFG spec was taking the SQRT of the % of total ETH supply at stake, rather than the number of ETH locked into validator deposits.  Should the 10000000 figure above be a percentage of total supply instead?

**Reward/epoch | 10000000/6475776*2 = 3088**

The equation above equals 3.088.  We are off by 3 decimal places for some reason. 

Any help/clarification on the above is much appreciated!

**Comment by econoar** [comment]
Hey! Thanks a lot for the help. You're indeed right that should be blocks/epoch.

For the reward quotient question, I feel that calc is right because if not the issuance numbers are way off. Maybe I'm missing something though?

Definitely on rewards/epoch too, a typo.

Fixing the 2 typos now, thanks!

**Comment by DigitalAssetAdvisors** [comment]
If we adjust Reward/epoch to be 3.088, then we must adjust the subsequent formula:
Generated ETH/Year | 82125***3088** = 253638

In the formulas provided, this would reduce validator interest/year to 0.0245%.  Something is off with the math.

**Comment by econoar** [comment]
82125*3088 = 253,602 ETH a year to validators. 

253602/10000000= 0.0253602 * 100 = 2.53% interest a year.

I fixed the 3088 but I think the rest is fine.
