### ISSUE TITLE
Sample Kickstarter (ETHstarter) smart contract

### ISSUE THREAD

**Issue by Hex-Capital** [ethhub-io/ethhub#85]
Draft of ETHstarter (Kickstarter) contract attached

Administrators
- Launch ETHstarter campaign by deploying contract
- Set fundraisingGoal in ETH
- Set EndTime (max of 30 days from launch)
- Set wallet address for withdrawing funds (if campaign reaches fundraisingGoal)
- Option to cancel the campaign before endTime if fundraisingGoal has not been met

Contributors
- Send contributions until fundraisingGoal or endTime is reached
- Withdraw contribution if endTime is reached before fundraisingGoal

Requesting community input, code review, and auditing!

Disclaimer: Smart contract draft only. Not ready for production-level deployment. I am not responsible for loss of funds!

[ETHstarter.zip](https://github.com/ethhub-io/ethhub/files/2693272/ETHstarter.zip)

**Comment by sassal** [comment]
Awesome work - thank you! This will be a great starting point to build upon.

**Comment by vs77bb** [comment]
Hi friends, Vivek from Gitcoin here. We have something called [Gitcoin Grants](https://gitcoin.co/grants/) which might be right up your alley. If you 👍this message I'll get you Admin access to the MVP, which will be out in the wild very soon 🙂 

We're hoping it will be a place where the most important projects get community support + get the fundraising they need to move forward the ecosystem. Let me know if you have any questions!

**Comment by ChazSchmidt** [comment]
> Hi friends, Vivek from Gitcoin here. We have something called [Gitcoin Grants](https://gitcoin.co/grants/) which might be right up your alley. If you +1this message I'll get you Admin access to the MVP, which will be out in the wild very soon slightly_smiling_face
> 
> We're hoping it will be a place where the most important projects get community support + get the fundraising they need to move forward the ecosystem. Let me know if you have any questions!

How long until grants are publicly available? Would it make sense to ever have a fund raising event/contract like this feed into a grant's subscription contract?

**Comment by ChazSchmidt** [comment]
This also might be useful for something like this https://github.com/ethereum/EIPs/issues/1620

**Comment by ChazSchmidt** [comment]
Are we able to close this now that Gitcoin Grant matching is happening?
