### ISSUE TITLE
no response on commit after some back and fourth

### ISSUE THREAD

**Issue by chanan-sack** [ethhub-io/ethhub#88]
improved answers to both questions 1 & 7 and after making a pull request and some back and fourth - stopped getting feedback, the changes are important and should not be overlooked.

on a more serious note: my corrected answer to question 1 actually replaces the currect incorrect answer, this is pretty serious if we want to actually provide usefull input.

**Comment by chanan-sack** [comment]
on a more serious note: my corrected answer to question 1 actually replaces the currect incorrect answer, this is pretty serious if we want to actually provide usefull input.

**Comment by ChazSchmidt** [comment]
I responded with feedback

**Comment by chanan-sack** [comment]
got it, if i improve the answers according to your feedback - will they be merged? its important because of the current incorrect one. so im just making sure that i wont be working on them for nothing..
