### ISSUE TITLE
Fork an already developed fundraising platform with built-in governance for the Ethereum Fundraising Event

### ISSUE THREAD

**Issue by AdrianClv** [ethhub-io/ethhub#90]
Hi,

I'm the CTO of Coin Governance System (https://cgs.vote/), an on-chain governance mechanism to manage funds in escrow between the donors and the receiver. It was initially developed to improve how funds are managed in an ICO (like DAICO, see https://medium.com/coin-governance-system/daico-and-coin-governance-system-differences-and-similarities-81ba6afc7b9b), but it can also be used to fund non-ICO projects (issuing a token with no value and governance rights only).

It already have the smart contracts, front-end, dashboards, etc. that have been tested for months.
It can be easily forked to remove any need for a token. So my proposal is to just fork it, make the needed modifications and use it to avoid implementing something from scratch.
A sample version working on kovan testnet can be seen here: https://testnet.cgs.vote/

**Comment by ChazSchmidt** [comment]
This is interesting. How would the dispute system work with ETH instead of tokens?

**Comment by AdrianClv** [comment]
The idea would be to issue a token for every project that accept donations. These tokens will have no value and will be used only to open a claim in the project.

The arbitration mechanism could use either Ether (working in the same way), or issuing a new token with no value that would be distributed among well-known members of the community/Ethereum Community Fund/etc.
