### ISSUE TITLE
Advertisements on EthHub

### ISSUE THREAD

**Issue by ChazSchmidt** [ethhub-io/ethhub#92]
With all the talk of raising funds for devs, I thought I'd throw this out there to get more opinions on the matter.

How does the community feel about advertising on EthHub? The revenue from the ads could go to the maintenance of the site and any additional income could be used to support developers. A service like [CodeFund](https://codefund.io/) might be an option. Obviously, the ads would have to be heavily monitored and curated for tasteful ads. It should also be **very clear** to newbies that any ads they see are advertisements and not part of the learning materials.

**Comment by sassal** [comment]
@econoar have discussed funding mechanisms for EthHub extensively. We probably want to keep advertising to just the podcast and newsletter (and not on the EthHub website itself).

List of ideas we've had so far:
- EthHub merch shop (t-shirts, stickers, art pieces etc)
- Patreon and/or Staketree
- Sponsored spots (podcast, newsletter)
- Referral links and promo codes

All revenue generated would go back into growing and maintaining EthHub. A detailed post about funding mechanisms is forthcoming :)

**Comment by Destiner** [comment]
I think one way to do this is to make some kind of "sponsors" section. Ads are obtrusive and overall have bad user experience, but putting a small image of the sponsor project is fine IMO. For example, say 0x becomes a sponsor and we put their logo and link in the corner. No messages, no offers, just logo.

Here's an example of that on [Vue developer docs](https://vuejs.org/v2/guide/) (on the right).

**Comment by cyber-hokie** [comment]
I guess the question is, how do you commoditize that so you can contribute it to the developer fund?

**Comment by RexShinka** [comment]
A subscription on GitCoin might be another avenue.

**Comment by sassal** [comment]
Thanks for all the input everyone! We've got a post coming out during the week that summarizes all our thoughts around advertisements/monetization strategies - stay tuned!
